-- ============================================================
-- SEED: Inventario Ingeniería / División Servicio
-- Generado: 2026-04-17 15:51
-- Fuente: INVENTARIO POR NUMERO DE CAJAS.xlsx (hoja INV)
-- Repuestos: 231 | Líneas: 4 | Cajas: 15
-- ============================================================

USE DB_EInventory;

-- ============================================================
-- 1. LÍNEAS  (TB_ENG_LINE)
-- ============================================================
INSERT INTO TB_ENG_LINE (LINE_NAME, LINE_GROUP, LINE_DESC, ACTIVE)
SELECT 'FASC DUET', NULL, NULL, 1
WHERE NOT EXISTS (SELECT 1 FROM TB_ENG_LINE WHERE LINE_NAME = 'FASC DUET');

INSERT INTO TB_ENG_LINE (LINE_NAME, LINE_GROUP, LINE_DESC, ACTIVE)
SELECT 'FASC LYRIC', NULL, NULL, 1
WHERE NOT EXISTS (SELECT 1 FROM TB_ENG_LINE WHERE LINE_NAME = 'FASC LYRIC');

INSERT INTO TB_ENG_LINE (LINE_NAME, LINE_GROUP, LINE_DESC, ACTIVE)
SELECT 'FUJIFILM', NULL, NULL, 1
WHERE NOT EXISTS (SELECT 1 FROM TB_ENG_LINE WHERE LINE_NAME = 'FUJIFILM');

INSERT INTO TB_ENG_LINE (LINE_NAME, LINE_GROUP, LINE_DESC, ACTIVE)
SELECT 'OCD', NULL, NULL, 1
WHERE NOT EXISTS (SELECT 1 FROM TB_ENG_LINE WHERE LINE_NAME = 'OCD');

-- ============================================================
-- 2. CAJAS  (TB_ENG_BOX)
-- ============================================================
INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 16, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'FASC DUET'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 16);

INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 17, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'FASC DUET'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 17);

INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 14, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'FASC LYRIC'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 14);

INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 15, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'FASC LYRIC'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 15);

INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 12, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'FUJIFILM'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 12);

INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 13, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'FUJIFILM'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 13);

INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 1, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'OCD'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 1);

INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 2, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'OCD'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 2);

INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 3, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'OCD'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 3);

INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 4, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'OCD'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 4);

INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 5, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'OCD'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 5);

INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 6, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'OCD'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 6);

INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 7, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'OCD'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 7);

INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 8, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'OCD'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 8);

INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 9, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'OCD'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 9);

INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 10, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'OCD'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 10);

INSERT INTO TB_ENG_BOX (LINE_CODE, BOX_NUMBER, BOX_DESC, ACTIVE)
SELECT l.LINE_CODE, 11, NULL, 1
  FROM TB_ENG_LINE l
 WHERE l.LINE_NAME = 'OCD'
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_BOX b2
        WHERE b2.LINE_CODE = l.LINE_CODE AND b2.BOX_NUMBER = 11);

-- ============================================================
-- 3. REPUESTOS  (TB_ENG_PART)
-- ============================================================
INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09569', 'CABLE PWR SUPPLY YZ PIPA', 3, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 1
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09569');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01021', 'LABEL BARCODE SET TUBE', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 1
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01021');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01092', 'COUPLING NS4 GREY LSYS', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 1
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01092');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01093', 'COUPLING NS4 BLUE LSYS', 10, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 1
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01093');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01094', 'COPLING NS4 GRAY LSYS', 17, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 1
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01094');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01098', 'PUMP CXP LSYS', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 1
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01098');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02955', 'INSULATION BLOCK PIPA', 5, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 1
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02955');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D06036', 'PUMP FAWA LSYS', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 1
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D06036');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09570', 'CABLE POW YZRG GRIP', 3, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 1
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09570');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09572', 'CABLE RSH 8*0.5 MM GRIP', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 1
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09572');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09573', 'CABLE RSH 8*0.5 MM PIPA', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 1
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09573');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09575', 'TUBE PVC FILTER SENSOR', 7, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 1
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09575');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09576', 'PCBA YZ PIPA VISION MAX', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 1
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09576');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09674', 'PCBA CONTROL INST VISION', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 1
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09674');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01110', 'BOX REFL FRONT LIGHT CIMS', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01110');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D00265', 'SET FUSE 12.5 A', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D00265');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D00596', 'SYRINGE1.25 ML LSYS', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D00596');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01003', 'CABLE HALL ENCODER', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01003');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01004', 'INS BLOCK READ ASSY PIPA', 4, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01004');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01007', 'SYRINGE CXP', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01007');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01008', 'TIP PIPETTE CONICAL LSYS', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01008');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01017', 'PCBA SENSE UNIV GRIP', 7, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01017');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01030', 'ASSY MOTOR COVER SRDR', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01030');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01051', 'PCBA Z-ROT GRIP', 4, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01051');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01054', 'CABLE CLLD650 MM', 5, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01054');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01055', 'NUT TIP LSYS', 5, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01055');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01056', 'ORINGS LSYS', 3, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01056');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01059', 'SRDR BC READER', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01059');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01061', 'TUBE PVC BLUE', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01061');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01062', 'TUBE PVC TRANPARENT', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01062');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01063', 'SET TUBE FILTER SENSE DEST', 4, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01063');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01064', 'TUVE FILTER VALVE', 4, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01064');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01066', 'TUBING SET PIPETING', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01066');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09091', 'BATERIAS DE PIPETA', 5, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09091');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09563', 'PCBA CONTROL INST', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09563');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09568', 'SET TUBE FILTER SENSE', 3, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09568');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09571', 'CABLE CLLD 150 MM', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 2
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09571');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01077', 'PWR SUPPLY 24 V 648 W', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 3
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01077');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01015', 'MOTOR R DRIVE GRIP', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 3
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01015');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01090', 'DISCO DE ESTADO SOLIDO', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 3
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01090');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01091', 'COUPLIN NS4 BLUE LSYS', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 3
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01091');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01109', 'PLATE DIFF BACK CIMS', 5, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 3
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01109');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01111', 'COVER LIGHT REFL', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 3
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01111');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07108', 'PCBA CLLD PIPA', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 3
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07108');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09151', 'LLAVE DE PASO AZUL', 4, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 3
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09151');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01075', 'PCBA GRIP Z ROT ASSY', 4, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 4
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01075');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01005', 'SENSOR HALL', 3, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 4
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01005');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01050', 'SET CABLE FLAT Z ROT', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 4
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01050');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D00266', 'SWITH PRESENCE LSYS', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 4
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D00266');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D00267', 'MOTOR G DRIVE GRIP', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 4
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D00267');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01002', 'VALVE 2/3 WAY LSYS', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 4
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01002');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01072', 'MOTOR Z DRIVE ASSY PIPA', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 4
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01072');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01081', 'MOTOR Z -DR.AND SHA GRIP', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 4
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01081');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D00264', 'CABLE FNF 1.8 M CINC', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 4
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D00264');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01011', 'CABLE FNF 1.8 M CINC', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 4
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01011');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D00590', 'FAWA PUMP LSYS', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 4
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D00590');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D00269', 'PELTIER ASSY SRDR', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 5
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D00269');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01010', 'KIT MP ANUAL  VISION BASE', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 5
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01010');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01057', 'PCBA MOTION INST', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 5
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01057');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01058', 'PCBA TP-HU-CHAS SRDR CINC', 3, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 5
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01058');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01068', 'PCBA FFC ADAT CINC', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 5
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01068');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01069', 'PCBA FFC ADAT STR CINC', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 5
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01069');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01070', 'PCBA PANEL LEFT CHAS', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 5
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01070');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01073', 'ASSY HALL SENSOR SRDR', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 5
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01073');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01079', 'MOTOR Z1 ASSY PIPA', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 6
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01079');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01029', 'MAINTENANCE KIT VISION BASE', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 6
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01029');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01071', 'LIQUID WASH CONTAINER', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 6
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01071');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01074', 'MANTENENACE KIT VISION MAX', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 6
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01074');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01080', 'MOTOR Z2 AASY PIPA', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 6
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01080');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01084', 'FILTER WHEEL ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01084');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D00466', 'GANCHOS VITROS', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D00466');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01032', 'SOFTWARE 3.6.1', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01032');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01042', 'SECONDARY TIP STREPPER FLE', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01042');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07041', 'OPTICAL SWITCH', 3, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07041');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07044', 'SENSOR', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07044');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07045', 'OPTICAL SENSOR ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07045');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07046', 'OPTICAL SENSOR ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07046');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07091', 'HARNESS REFERENCE', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07091');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07096', 'ASSY LINEAR ACTUATOR', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07096');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07101', 'ESCAPEMENT ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07101');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09500', 'SLIDE KICKER ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09500');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09517', 'RH BOX ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09517');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09521', 'HUMIDITY PLATE ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09521');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09522', 'DRIVE MOTOR ASSY PM', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09522');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09523', 'FS REFL HOUSING FRU', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09523');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09524', 'POST BUSHING BEARING CM', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09524');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09527', 'IDLER SPRING', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09527');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09528', 'BLADE INSERT', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09528');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09529', 'PINION AY PROBOSIS', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09529');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09532', 'ENCODER ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09532');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09533', 'MOTOR ASSY STEPER WGA', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09533');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09534', 'FAN ASSY', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09534');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09542', 'COVER ASSY INCUBATOR', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09542');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09544', 'BELT TIMING T2.5 420', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09544');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09548', 'TRANSDUCER BOARD ORING', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09548');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09553', 'PM RING V BEARING ASSY', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09553');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09564', 'WHITE REFERENCE ASSY', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 7
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09564');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D00459', 'SUPERLUBE', 6, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D00459');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01043', 'TOWER TIP SEAL EJECT', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01043');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09551', 'KIT  FLEPPER ASSY', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09551');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01045', 'ROLER WASH SHUTTLE', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01045');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01044', 'SPRING RETAINER', 3, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01044');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01046', 'BEARING CAM', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01046');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09559', 'BLADE HOUSING & COVER ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09559');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01041', 'CABLE FLEX REAGENT SUPPLY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01041');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01047', 'PM LABEL', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01047');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09519', 'FAN DC REFLEC', 1, 'KIT PM'
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09519');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09555', 'FILTER FAN', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09555');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09556', 'FILTER LINEAR PUMP', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09556');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07042', 'BEARING PADS', 3, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07042');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09553', 'IR WASH CAM', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09553');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D00488', 'WASHERCAM', 6, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D00488');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09526', 'BLADE CM EJECT', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09526');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09537', 'BLADE DISPENSE MOLDED', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09537');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09512', 'CARRIER PROBOSIS ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09512');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09516', 'SECUNDARY TIP SEALER', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09516');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09567', 'ROLER KICKER', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09567');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01083', 'SUPORT WHITE REFERENCE', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01083');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09513', 'PRIMARY TIP SEALER', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09513');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09525', 'CM EJECT PLATE ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09525');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09509', 'TIP SEALER SECONDARY', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09509');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09546', 'TUBING FS 5.1', 4, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09546');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07092', 'LEAK TEST PAD', 4, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07092');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09531', 'BLADE', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09531');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09501', 'PROBOSIS ASSY', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 8
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09501');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07107', 'METERING DSP PWBA', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07107');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07089', 'SECONDARY TIP STRPPER FLEX', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07089');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07093', 'BELT TIMING T2 5 600', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07093');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07094', 'CABLE, W/FERRITES ELECTROM', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07094');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07095', 'SWITCH INTELOCK', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07095');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07097', 'DROP SENSOR', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07097');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07098', 'BELT KIT , ORING , MICROTIP', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07098');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07099', 'PWBA FOTOMETER DSP', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07099');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07100', 'GEAR MOTOR ASEMBLY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07100');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07102', 'MOTOR NUT LEAD SCREW', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07102');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07103', 'MOTOR PULLEY ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07103');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07104', 'TIMING BELT', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07104');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07105', 'OPTICAL SENSOR ASSY PLUG', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07105');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D07106', 'SPRING DOOR', 3, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D07106');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09514', 'MIRROR ILUMINATOR LENS', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09514');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09515', 'COLECTION  ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09515');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09520', 'ELECTROMETER ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09520');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09530', 'DISPENSE BLADE ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09530');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09550', 'DRIVE PULLEY ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09550');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09566', 'PCBA REFLECTOMETER', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 9
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09566');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09547', 'DISCO DURO PC', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 10
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09547');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09552', 'MOTOR BRACKET ASSSY', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 10
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09552');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09510', 'SAMPLE PUMP', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 10
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09510');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09543', 'HIGH POWER DSP', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 10
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09543');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09511', 'LOW POWER DSP', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 10
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09511');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09506', 'PLUNGGER ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 10
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09506');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09558', 'TRUMOTION BELT', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 10
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09558');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09536', 'OPTICAL FIBER', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 10
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09536');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09541', 'POWER SUPPLY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 11
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09541');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09540', 'POWER SUPPLY 2', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 11
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09540');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09507', 'SAMPLE METERING PUMP', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 11
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09507');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D09549', 'LAMP ASSEMBLY', 3, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 11
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D09549');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D01082', 'ILUMINATION FIBER', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'OCD' AND b.BOX_NUMBER = 11
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D01082');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04097', 'FOTOMETER HEAD ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04097');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04151', 'IMPRESORA VIEJA NX500', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04151');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04175', 'MANGUERAS NX500', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04175');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04079', 'FILTER WHEEL', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04079');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04170', 'JERINGA NX600', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04170');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04176', 'ARD NX500', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04176');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04165', 'IMPRESORA FUJIFILM', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04165');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04171', 'JERINGA NX500', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04171');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04099', 'LENTE DE LAMPARA', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04099');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04150', 'IMPRESORA', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04150');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04155', 'TIMING BELT', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04155');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04156', 'TIMING BELT', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04156');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04157', 'TIMING BELT', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04157');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04158', 'TIMING BELT', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04158');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04159', 'TIMING BELT', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04159');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04154', 'FAN', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04154');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04153', 'FAN', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04153');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04098', 'OPTICAL FIBER', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04098');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04077', 'LABEL RACK', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04077');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04152', 'DAMPER', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04152');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04089', 'PINS FOR SAMPLE RACK', 3, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04089');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04093', 'SPACER 0.25 MM', 7, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04093');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04094', 'SPACER 0.13 MM', 4, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04094');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04179', 'INCUBATOR CABLE', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 12
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04179');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04119', 'INCUBATOR NX600', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04119');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04149', 'DISPLAY NX600', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04149');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04180', 'PANEL UNIT NX700', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04180');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04175', 'TUBE', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04175');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04168', 'SENSOR OPTICO', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04168');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04163', 'TRANSDUCTOR NX500', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04163');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04169', 'SESNORES DE PUNTAS NX500', 3, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04169');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04164', 'ARD NX600', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04164');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04168', 'SENSOR OPTICO', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04168');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04096', 'SLIDE WEIGHT', 8, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04096');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04174', 'BOX SLIDE', 3, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04174');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04173', 'BOX SLIDE NX600', 5, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04173');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04177', 'PLAIN BEARING', 10, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04177');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04095', 'INCUBADOR SCREW', 40, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04095');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04167', 'TAPA FLUIDO REF', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04167');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04082', 'BOX SLIDE NX500', 3, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04082');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D04092', 'TERMINALES DE MANGUERA', 10, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FUJIFILM' AND b.BOX_NUMBER = 13
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D04092');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02563', 'MODULO SIP ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC LYRIC' AND b.BOX_NUMBER = 14
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02563');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02938', 'LOADER BOARD', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC LYRIC' AND b.BOX_NUMBER = 14
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02938');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02558', 'PROBOSIS SIP', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC LYRIC' AND b.BOX_NUMBER = 14
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02558');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02965', 'PUMP P4', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC LYRIC' AND b.BOX_NUMBER = 14
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02965');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02560', 'MANIFOLD', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC LYRIC' AND b.BOX_NUMBER = 14
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02560');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02964', 'SUBTANQUE FACSFLOW', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC LYRIC' AND b.BOX_NUMBER = 14
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02964');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02559', 'PUMPS', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC LYRIC' AND b.BOX_NUMBER = 14
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02559');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02936', 'PUMP P2/P5', 3, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC LYRIC' AND b.BOX_NUMBER = 14
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02936');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02962', 'DEGASIFICADOR KIT', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC LYRIC' AND b.BOX_NUMBER = 14
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02962');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02937', 'DEGASIFICADOR', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC LYRIC' AND b.BOX_NUMBER = 14
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02937');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02935', 'TRANSDUCER SWITCH', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC LYRIC' AND b.BOX_NUMBER = 14
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02935');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02562', 'SENSOR HALL SIP', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC LYRIC' AND b.BOX_NUMBER = 14
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02562');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02561', 'TRANSDUCER', 4, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC LYRIC' AND b.BOX_NUMBER = 14
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02561');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02974', 'LASER AZUL', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC LYRIC' AND b.BOX_NUMBER = 15
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02974');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02976', 'LASER VIOLETA', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC LYRIC' AND b.BOX_NUMBER = 15
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02976');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02975', 'LASER ROJO', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC LYRIC' AND b.BOX_NUMBER = 15
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02975');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02889', 'MP KIT YEARLY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC DUET' AND b.BOX_NUMBER = 16
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02889');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02876', 'SYRINGE 500 UL', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC DUET' AND b.BOX_NUMBER = 16
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02876');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02898', 'PUMP MEMBRANE NF60', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC DUET' AND b.BOX_NUMBER = 16
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02898');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02897', 'PUMP MEMBRANE NF30', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC DUET' AND b.BOX_NUMBER = 16
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02897');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02599', 'VALVE 3 WAYS', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC DUET' AND b.BOX_NUMBER = 16
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02599');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02894', 'CU TARJETA MADRE', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC DUET' AND b.BOX_NUMBER = 16
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02894');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02895', 'MANIFOLD', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC DUET' AND b.BOX_NUMBER = 16
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02895');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02892', 'PCBA POWER CAN', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC DUET' AND b.BOX_NUMBER = 16
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02892');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02972', 'PCB FRONT COVER CU', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC DUET' AND b.BOX_NUMBER = 16
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02972');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02940', 'TUBING, SPRP 2 DILUTER', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC DUET' AND b.BOX_NUMBER = 16
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02940');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02598', 'AGUJAS DE MUESTRA', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC DUET' AND b.BOX_NUMBER = 16
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02598');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02597', 'MANGUERAS PERISTALTICAS', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC DUET' AND b.BOX_NUMBER = 16
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02597');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02893', 'YZ DRIVE RIGTH ARM', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC DUET' AND b.BOX_NUMBER = 17
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02893');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02891', 'PIPETOR MAIN BOARD PCB', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC DUET' AND b.BOX_NUMBER = 17
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02891');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02939', 'TUBING SPOLV, RIGTH ARM', 2, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC DUET' AND b.BOX_NUMBER = 17
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02939');

INSERT INTO TB_ENG_PART (BOX_CODE, PART_REF, PART_NAME, PART_QTY, PART_NOTES)
SELECT b.BOX_CODE, 'D02896', 'PERISTALTIC PUMP ASSY', 1, NULL
  FROM TB_ENG_BOX b
  JOIN TB_ENG_LINE l ON l.LINE_CODE = b.LINE_CODE
 WHERE l.LINE_NAME = 'FASC DUET' AND b.BOX_NUMBER = 17
   AND NOT EXISTS (
       SELECT 1 FROM TB_ENG_PART p
        WHERE p.BOX_CODE = b.BOX_CODE AND p.PART_REF = 'D02896');

